// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo5wVhrg6_POXZxx5GDRroaFVcqYR4dtU',
    appId: '1:233410894442:android:7e22e9a315bdda668bc813',
    messagingSenderId: '233410894442',
    projectId: 'fittrack-28762',
    storageBucket: 'fittrack-28762.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo5wVhrg6_POXZxx5GDRroaFVcqYR4dtU',
    appId: '1:233410894442:ios:PLACEHOLDER',
    messagingSenderId: '233410894442',
    projectId: 'fittrack-28762',
    storageBucket: 'fittrack-28762.firebasestorage.app',
    iosBundleId: 'com.example.fittrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo5wVhrg6_POXZxx5GDRroaFVcqYR4dtU',
    appId: '1:233410894442:ios:PLACEHOLDER',
    messagingSenderId: '233410894442',
    projectId: 'fittrack-28762',
    storageBucket: 'fittrack-28762.firebasestorage.app',
    iosBundleId: 'com.example.fittrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo5wVhrg6_POXZxx5GDRroaFVcqYR4dtU',
    appId: '1:233410894442:windows:PLACEHOLDER',
    messagingSenderId: '233410894442',
    projectId: 'fittrack-28762',
    storageBucket: 'fittrack-28762.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo5wVhrg6_POXZxx5GDRroaFVcqYR4dtU',
    appId: '1:233410894442:web:PLACEHOLDER',
    messagingSenderId: '233410894442',
    projectId: 'fittrack-28762',
    storageBucket: 'fittrack-28762.firebasestorage.app',
    authDomain: 'fittrack-28762.firebaseapp.com',
  );
}
